filter:
    paths: ["core/src/*"]
    excluded_paths:
        - "core/src/*Bundle/Tests/"
    dependency_paths:
        - "core/vendor/"

checks:
    php:
        code_rating: true
        duplication: false
        excluded_dependencies:
            - npm-asset/marked
            - npm-asset/markdown-it-underline
            - npm-asset/github-markdown-css
            - npm-asset/simplemde
            - npm-asset/codemirror
            - gedmo/doctrine-extensions
