version: '3.4'
services:
  app:
    image: opensalt/app:${COMMIT}

  phpfpm:
    image: opensalt/php:7.4-fpm
    depends_on:
      - db
    environment:
      #XDEBUG_CONFIG: remote_host=Your_IP_Address
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_HOST: "${MYSQL_HOST:-db}"
      DB_USE_RDS_CERT:
      APP_SECRET:
      COOKIE_SECRET:
      GITHUB_CLIENT_ID:
      GITHUB_CLIENT_SECRET:
      BRAND_LOGO_URL:
      BRAND_LOGO_STYLE:
      BRAND_LINK_URL:
      BRAND_LINK_STYLE:
      FOOTER_LEFT_TEXT:
      ALLOW_LOCAL_DEV: "true"
      ALLOW_EXTERNAL_DEV_IPS:
      DEV_COOKIE:
      MAILER_TRANSPORT:
      MAILER_HOST:
      MAILER_USER:
      MAILER_PASSWORD:
      MAILER_AUTH_MODE:
      MAILER_PORT:
      COMMENTS_FEATURE:
      COMMENT_ATTACHMENTS:
      ATTACHMENT_URL_PREFIX:
      CREATE_ACCOUNT_FEATURE:
      USE_MAIL_FEATURE:
      MAIL_FEATURE_FROM_EMAIL:
      GOOGLE_CAPTCHA_SITE_KEY:
      GOOGLE_CAPTCHA_SECRET_KEY:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_S3_BUCKET:
      AWS_S3_REGION:
      AWS_S3_PREFIX:
      ATTACHMENT_URL_PREFIX:
      BUCKET_PROVIDER:
      LOCAL_FILESYSTEM_PATH:
      CASE_NETWORK_CLIENT_ID:
      CASE_NETWORK_CLIENT_SECRET:
      CASE_NETWORK_TOKEN_ENDPOINT:
      CASE_NETWORK_SCOPE:
      MERCURE_PUBLISH_URL:
      MERCURE_JWT_TOKEN:
    volumes_from:
      - app
    working_dir: /var/www/html

  nginx:
    image: opensalt/nginx:1.18-alpine
    depends_on:
      - phpfpm
    environment:
      UPSTREAM_HOST: phpfpm:9000
    volumes_from:
      - app
    working_dir: /var/www/html

  mercure:
    image: dunglas/mercure:v0.11
    environment:
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      MERCURE_TRANSPORT_URL: 'local://local'
      MERCURE_EXTRA_DIRECTIVES: "anonymous\nsubscriptions\ndemo"
      SERVER_NAME: ':80'
      DEBUG: 'debug'

  db:
    image: percona:${MYSQL_VERSION}
    volumes:
      - "${PROJ_DIR:-..}/docker/mysql/max_allowed_packet.cnf:/etc/mysql/conf.d/max_allowed_packet.cnf:ro"
      - "${PROJ_DIR:-..}/docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf:ro"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
